# Generated by Django 6.0.4 on 2026-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('tom_tat', models.TextField()),
                ('noi_dung', models.TextField()),
                ('anh_minh_hoa', models.ImageField(upload_to='tin_tuc/')),
                ('luot_xem', models.IntegerField(default=0)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BangDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_doi_bong', models.CharField(max_length=100)),
                ('so_tran', models.IntegerField(default=0)),
                ('diem_so', models.IntegerField(default=0)),
            ],
        ),
    ]
