# Generated by Django 6.0.4 on 2026-05-19 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thethao', '0002_baiviet_tac_gia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BangDiem',
        ),
        migrations.AddField(
            model_name='baiviet',
            name='the_loai',
            field=models.CharField(choices=[('bong_da', 'Bóng Đá'), ('bong_ro', 'Bóng Rổ'), ('tennis', 'Tennis'), ('cau_long', 'Cầu Lông'), ('dua_xe', 'Đua Xe F1'), ('vo_thuat', 'Võ Thuật'), ('esports', 'Esports')], default='bong_da', max_length=20),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='anh_minh_hoa',
            field=models.ImageField(blank=True, null=True, upload_to='anh_tin_tuc/'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tac_gia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
